Feature/error handling
indigotech/onboard-joao-bernardino pull request #21
Opened 2023-05-10 20:39 UTC by jpselva

[Melhora tratamento de erros, implementa testes para casos de erro](https://github.com/indigotech/onboard-joao-bernardino/issues/14#issuecomment-1542202596)

2023-05-11 12:02 UTC, iuri-unb requested changes

2023-05-11 12:02 UTC, iuri-unb commented on src/server.ts
> +    formatError: formatError,
```suggestion
    formatError,
```
Quando a variável tem o mesmo nome do parametro podemos simplificar!

2023-05-11 12:02 UTC, iuri-unb commented on src/base-error.ts
> +  constructor(public message: string, public code: number, public details: string) {
O que acha de deixar o details como nullable? Nem sempre você vai querer retornar detalhes de exceção

2023-05-11 12:02 UTC, iuri-unb commented on src/user-validation.ts
> +    return { validated: true, message: '', failureReason: '' };
Aqui poderia já utilizar o erro customizado que você implementou, o que acha? Mesma coisa pros outros validators

2023-05-11 12:02 UTC, iuri-unb commented on test/index.ts
> +    });
Acho válido separar esses casos de teste, fica mais legível e mais fácil de auditar caso algum teste falhe

2023-05-11 12:25 UTC, matheusflds commented on test/index.ts
> +    });
+1 pros pontos do Iuri! 
Lembrando ainda que cada teste deve ser independente (até por isso que limpamos o banco entre cada it), você deixar mais de um cenário num mesmo it pode fazer com que o segundo cenário tenha alguma influência do primeiro

2023-05-11 12:31 UTC, alanraso approved these changes

2023-05-11 12:31 UTC, alanraso commented on test/index.ts
> +    function makeInput(fields?: object) {
Aqui a funçãao acabou ficando tipada de forma muito genérica né? Que campos ela está esperando nesse objeto? Vc pode criar uma nova interface pra especficar isso ou compor com uma já existente. Por exempo um `Partial<User>`, que é um `User` com todos os campos opcionais.

2023-05-11 12:31 UTC, alanraso commented on test/index.ts
> +    });
É uma boa prática separar um caso de teste por it, porque assim fica mais fácil identificar e arrumar possíveis erros.

2023-05-11 12:48 UTC, jpselva commented on test/index.ts
> +      userRepository.save(existingUser);
Fiquei com uma dúvida aqui: como esses testes são end-to-end seria mais correto eu criar o usuário mandando um request com o axios? Isso seria mais próximo do funcionamento real do servidor (que é a ideia dos testes e2e, pelo o que eu entendi), mas iria contra a independência dos testes, já que envolveria a mutation `createUser`, que é responsabilidade de outro caso de teste.

2023-05-11 13:24 UTC, alanraso commented on test/index.ts
> +      userRepository.save(existingUser);
Nossos testes fazem um teste caixa preta de uma query ou mutation. E o setup dessa query/mutation pode ser o mais "baixo nível" possível. Ou seja, vc não precisa criar um usuário com a mutation `createUser` pra fazer setup desse teste, vc pode adicionar um usuário direto no banco, que seria o resultado "correto" de uma `createUser`. Assim vc garante a independência pq se a createUser tiver errada, vc n compromete esse teste.

2023-05-12 14:22 UTC, matheusflds approved these changes

2023-05-12 16:50 UTC, merged